// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lazy.proto

package config // import "github.com/noahdietz/lazyrpc/config"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The types of resource-oriented methods supported by lazyrpc.
// Learn more from https://cloud.google.com/apis/design.
type Method int32

const (
	Method_UNKOWN_METHOD Method = 0
	Method_CREATE        Method = 1
	Method_GET           Method = 2
	Method_LIST          Method = 3
	Method_UPDATE        Method = 4
	Method_DELETE        Method = 5
)

var Method_name = map[int32]string{
	0: "UNKOWN_METHOD",
	1: "CREATE",
	2: "GET",
	3: "LIST",
	4: "UPDATE",
	5: "DELETE",
}
var Method_value = map[string]int32{
	"UNKOWN_METHOD": 0,
	"CREATE":        1,
	"GET":           2,
	"LIST":          3,
	"UPDATE":        4,
	"DELETE":        5,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_lazy_e12a089d6278c937, []int{0}
}

// lazyrpc configuration fields for lazy generation of proto
// Service files.
type Config struct {
	// The list of RPCs to generate for the configured message.
	//
	// Example:
	//
	//  message Todo {
	//   option (lazy.config) = {
	//     methods: [CREATE, LIST, DELETE]
	//   };
	//
	// An empty list or option omission signals to skip a message
	Methods []Method `protobuf:"varint,1,rep,packed,name=methods,proto3,enum=lazy.Method" json:"methods,omitempty"`
	// The message field to be used as the key in GET & DELETE
	// methods.
	//
	// Example:
	//
	//  message Todo {
	//   option (lazy.config) = {
	//     methods: [GET, DELETE]
	//     key: "id"
	//   };
	//
	// If a key is not specified, the configured message in its
	// entirety is used as input.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The default host of the generated message-specific service.
	//
	// Example:
	//
	//  message Todo {
	//   option (lazy.config) = {
	//     methods: [CREATE, LIST]
	//     default_host: "api.todos.com"
	//   };
	//
	// The value is injected as a proto Service option google.api.default_host
	// defined at https://github.com/googleapis/api-common-protos.
	DefaultHost          string   `protobuf:"bytes,3,opt,name=default_host,json=defaultHost,proto3" json:"default_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_lazy_e12a089d6278c937, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetMethods() []Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Config) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Config) GetDefaultHost() string {
	if m != nil {
		return m.DefaultHost
	}
	return ""
}

var E_Config = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Config)(nil),
	Field:         4494,
	Name:          "lazy.config",
	Tag:           "bytes,4494,opt,name=config",
	Filename:      "lazy.proto",
}

func init() {
	proto.RegisterType((*Config)(nil), "lazy.Config")
	proto.RegisterEnum("lazy.Method", Method_name, Method_value)
	proto.RegisterExtension(E_Config)
}

func init() { proto.RegisterFile("lazy.proto", fileDescriptor_lazy_e12a089d6278c937) }

var fileDescriptor_lazy_e12a089d6278c937 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x5f, 0x4f, 0xf2, 0x30,
	0x18, 0xc5, 0xdf, 0x31, 0xde, 0xa1, 0x0f, 0x68, 0x6a, 0xaf, 0x16, 0x6f, 0x9c, 0x9a, 0x18, 0x42,
	0x4c, 0x97, 0xe8, 0x9d, 0x5e, 0x29, 0x54, 0x31, 0xf2, 0xc7, 0xcc, 0x11, 0x13, 0x6f, 0xc8, 0xd8,
	0xca, 0xb6, 0x08, 0x3c, 0xcb, 0x5a, 0x2e, 0xe0, 0x43, 0xf8, 0x99, 0x4d, 0x57, 0x76, 0xd5, 0x93,
	0x73, 0x4e, 0x4f, 0xfb, 0x03, 0x58, 0x45, 0xfb, 0x1d, 0x2b, 0x4a, 0x54, 0x48, 0x9b, 0x5a, 0x9f,
	0x7b, 0x29, 0x62, 0xba, 0x12, 0x7e, 0xe5, 0x2d, 0xb6, 0x4b, 0x3f, 0x11, 0x32, 0x2e, 0xf3, 0x42,
	0x61, 0x69, 0x7a, 0x57, 0x02, 0x9c, 0x3e, 0x6e, 0x96, 0x79, 0x4a, 0x6f, 0xa0, 0xb5, 0x16, 0x2a,
	0xc3, 0x44, 0xba, 0x96, 0x67, 0x77, 0x4f, 0xef, 0x3a, 0xac, 0xda, 0x1b, 0x57, 0x66, 0x50, 0x87,
	0x94, 0x80, 0xfd, 0x23, 0x76, 0x6e, 0xc3, 0xb3, 0xba, 0xc7, 0x81, 0x96, 0xf4, 0x12, 0x3a, 0x89,
	0x58, 0x46, 0xdb, 0x95, 0x9a, 0x67, 0x28, 0x95, 0x6b, 0x57, 0x51, 0xfb, 0xe0, 0x0d, 0x51, 0xaa,
	0x5e, 0x00, 0x8e, 0xd9, 0xa1, 0x67, 0x70, 0x32, 0x9b, 0xbc, 0x4f, 0xbf, 0x26, 0xf3, 0x31, 0x0f,
	0x87, 0xd3, 0x01, 0xf9, 0x47, 0x01, 0x9c, 0x7e, 0xc0, 0x9f, 0x42, 0x4e, 0x2c, 0xda, 0x02, 0xfb,
	0x95, 0x87, 0xa4, 0x41, 0x8f, 0xa0, 0x39, 0x7a, 0xfb, 0x0c, 0x89, 0xad, 0xe3, 0xd9, 0xc7, 0x40,
	0xc7, 0x4d, 0xad, 0x07, 0x7c, 0xc4, 0x43, 0x4e, 0xfe, 0x3f, 0xbc, 0x80, 0x13, 0x9b, 0xaf, 0x5f,
	0x30, 0xc3, 0xc9, 0x6a, 0x4e, 0x36, 0x16, 0x52, 0x46, 0xa9, 0x98, 0x16, 0x2a, 0xc7, 0x8d, 0x74,
	0x7f, 0xaf, 0x3d, 0xab, 0xdb, 0xae, 0x89, 0x0c, 0x70, 0x70, 0xb8, 0xfd, 0x7c, 0xfb, 0xdd, 0x4b,
	0x73, 0x95, 0x6d, 0x17, 0x2c, 0xc6, 0xb5, 0xbf, 0xc1, 0x28, 0x4b, 0x72, 0xa1, 0xf6, 0xbe, 0xee,
	0x96, 0x45, 0xec, 0x9b, 0xda, 0xa3, 0x39, 0x16, 0x4e, 0xf5, 0xc6, 0xfd, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x24, 0xae, 0x96, 0x42, 0x6d, 0x01, 0x00, 0x00,
}
